---
title: "Example"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Guideline

- `###` : 예제 제목
- `####` : 학번 및 이름
- 그 아래는 자유롭게 구성 (설명 / 코드 / 그림 등)
- 아래 이미 생성되어 있는 예제처럼 작성하면 된다.

## Examples

### Vector Operations in R

#### 학번 : 21234567 / 이름 : 홍길동

이 예제를 포함하여, 다른 학생의 예제를 삭제하지 않음.
두 개의 벡터를 생성하고, dot product를 계산한다. 두 가지 방법으로 해 본다.


```{r}
x <- c(1, 2, 3, 4, 5)
y <- c(5, 4, 3, 2, 1)
sum(x * y)
```
```{r}
t(x) %*% y
```

### 동전을 10번 던졌을 때 앞면이 나오는 횟수 1000번 시뮬레이션하고, 평균 계산

#### 학번 : 22410403 / 이름 : 김나현

```{r}
set.seed(100)

n <- 10
n_s <- 1000
results <- replicate(n_s, sum(sample(c(1,0), n, replace = TRUE)))

head(results)

mean_heads <- mean(results)
mean_heads
```

### 시뮬레이션한 결과를 바탕으로 히스토그램을 그려 분포를 확인하고, 각 횟수의 확률 계산

#### 학번 : 22410403 / 이름 : 김나현

```{r}
hist(results, breaks = 0 : (n+1)-0.5, col = "lightblue",
     main = "10회 동전 던지기 시뮬레이션(1000회)",
     xlab = "앞면이 나온 횟수", ylab = "빈도")

abline(v = mean_heads, col = "blue", lwd = 2)
text(mean_heads+0.5, 120, paste0("평균 = ", round(mean_heads,2)), col = "blue")

# 0~10 앞면이 나올 확률 계산
table(results)/n
```

